/* eslint-disable */
// This file is auto-generated by scripts/generate-staff-list.mjs.
// Do not edit manually.

import dayStaff51989388 from "./day-staff/51989388.json";

export type DayStaff = {
  name: string;
  image: string;
  href?: string;
};

export const DAY_STAFF_LIST: DayStaff[] = [dayStaff51989388];
