/* eslint-disable */
// This file is auto-generated by scripts/generate-staff-list.mjs.
// Do not edit manually.



export type DayStaff = {
  name: string;
  image: string;
  href?: string;
};


export const DAY_STAFF_LIST: DayStaff[] = [

];
