/* eslint-disable */
// This file is auto-generated by scripts/generate-staff-list.mjs.
// Do not edit manually.

import dayStaff41291352 from "./day-staff/41291352.json";

export type DayStaff = {
  name: string;
  image: string;
  href?: string;
};

export const DAY_STAFF_LIST: DayStaff[] = [dayStaff41291352];
