// Auto-generated by scripts/generate-staff-list.mjs. Do not edit manually.
import staff0 from "./staff/109256327.json";
import staff1 from "./staff/123361035.json";
import staff2 from "./staff/129603409.json";
import staff3 from "./staff/131174171.json";
import staff4 from "./staff/131508158.json";
import staff5 from "./staff/148971304.json";
import staff6 from "./staff/152772067.json";
import staff7 from "./staff/155987338.json";
import staff8 from "./staff/165040846.json";
import staff9 from "./staff/21189750.json";
import staff10 from "./staff/24271196.json";
import staff11 from "./staff/24590869.json";
import staff12 from "./staff/25561744.json";
import staff13 from "./staff/27627295.json";
import staff14 from "./staff/39510845.json";
import staff15 from "./staff/40641235.json";
import staff16 from "./staff/41561321.json";
import staff17 from "./staff/4177010.json";
import staff18 from "./staff/44350989.json";
import staff19 from "./staff/47011206.json";
import staff20 from "./staff/48115683.json";
import staff21 from "./staff/49489155.json";
import staff22 from "./staff/62867580.json";
import staff23 from "./staff/63735116.json";
import staff24 from "./staff/64204237.json";
import staff25 from "./staff/64731817.json";
import staff26 from "./staff/76100848.json";
import staff27 from "./staff/77495217.json";
import staff28 from "./staff/78304794.json";
import staff29 from "./staff/78792577.json";
import staff30 from "./staff/7902223.json";
import staff31 from "./staff/807519.json";
import staff32 from "./staff/86270681.json";
import staff33 from "./staff/95003927.json";
import staff34 from "./staff/95559965.json";

export const staffListData = [
  staff0,
  staff1,
  staff2,
  staff3,
  staff4,
  staff5,
  staff6,
  staff7,
  staff8,
  staff9,
  staff10,
  staff11,
  staff12,
  staff13,
  staff14,
  staff15,
  staff16,
  staff17,
  staff18,
  staff19,
  staff20,
  staff21,
  staff22,
  staff23,
  staff24,
  staff25,
  staff26,
  staff27,
  staff28,
  staff29,
  staff30,
  staff31,
  staff32,
  staff33,
  staff34,
];
