/* eslint-disable */
// This file is auto-generated by scripts/generate-staff-list.mjs.
// Do not edit manually.

import staff807519 from "./staff/807519.json";
import staff4177010 from "./staff/4177010.json";
import staff7902223 from "./staff/7902223.json";
import staff21189750 from "./staff/21189750.json";
import staff24271196 from "./staff/24271196.json";
import staff24590869 from "./staff/24590869.json";
import staff25561744 from "./staff/25561744.json";
import staff27627295 from "./staff/27627295.json";
import staff28555457 from "./staff/28555457.json";
import staff39510845 from "./staff/39510845.json";
import staff40641235 from "./staff/40641235.json";
import staff41561321 from "./staff/41561321.json";
import staff44350989 from "./staff/44350989.json";
import staff47011206 from "./staff/47011206.json";
import staff48115683 from "./staff/48115683.json";
import staff49489155 from "./staff/49489155.json";
import staff62867580 from "./staff/62867580.json";
import staff63735116 from "./staff/63735116.json";
import staff64204237 from "./staff/64204237.json";
import staff64731817 from "./staff/64731817.json";
import staff76100848 from "./staff/76100848.json";
import staff77495217 from "./staff/77495217.json";
import staff78304794 from "./staff/78304794.json";
import staff78792577 from "./staff/78792577.json";
import staff86270681 from "./staff/86270681.json";
import staff95003927 from "./staff/95003927.json";
import staff95559965 from "./staff/95559965.json";
import staff109256327 from "./staff/109256327.json";
import staff123361035 from "./staff/123361035.json";
import staff129603409 from "./staff/129603409.json";
import staff131174171 from "./staff/131174171.json";
import staff131508158 from "./staff/131508158.json";
import staff148971304 from "./staff/148971304.json";
import staff152772067 from "./staff/152772067.json";
import staff155987338 from "./staff/155987338.json";
import staff165040846 from "./staff/165040846.json";
import staff175666619 from "./staff/175666619.json";

export const staffList = [
  staff807519,
  staff4177010,
  staff7902223,
  staff21189750,
  staff24271196,
  staff24590869,
  staff25561744,
  staff27627295,
  staff28555457,
  staff39510845,
  staff40641235,
  staff41561321,
  staff44350989,
  staff47011206,
  staff48115683,
  staff49489155,
  staff62867580,
  staff63735116,
  staff64204237,
  staff64731817,
  staff76100848,
  staff77495217,
  staff78304794,
  staff78792577,
  staff86270681,
  staff95003927,
  staff95559965,
  staff109256327,
  staff123361035,
  staff129603409,
  staff131174171,
  staff131508158,
  staff148971304,
  staff152772067,
  staff155987338,
  staff165040846,
  staff175666619,
];
