export const EVENT_DATE = {
  DAY1: "2025-03-23",
  DAY2: "2025-03-24",
} as const;
export type EventDate = keyof typeof EVENT_DATE;

export const TRACK = {
  TRACK1: {
    name: "トグルルーム",
    tag: "#tskaigi_toggle",
  },
  TRACK2: {
    name: "アセンドトラック",
    tag: "#tskaigi_ascend",
  },
  TRACK3: {
    name: "レバレジーズトラック",
    tag: "#tskaigi_leverages",
  },
} as const;
export type Track = keyof typeof TRACK;

export const TALK_TYPE = {
  SESSION: {
    name: "セッション",
    color: "#0C7EDC",
  },
  INVITATION: {
    name: "招待講演",
    color: "#0CA90E",
  },
  ORGANIZER: {
    name: "主催者講演",
    color: "#0CA90E",
  },
  LT: {
    name: "LT",
    color: "#c3620f",
  },
  SPONSOR_LT: {
    name: "スポンサーLT",
    color: "#E53D84",
  },
  EVENT: {
    name: "現地参加者向け企画",
    color: "#E02527",
  },
};
export type TalkType = keyof typeof TALK_TYPE;

export type Speaker = {
  name: string;
  username?: string;
  profileImagePath?: string;
  bio?: string;
  xId?: string;
  githubId?: string;
  additionalLink?: string;
  affiliation?: string;
  position?: string;
  company?: string;
};

export type Talk = {
  id: string;
  eventDate: EventDate;
  track: Track;
  talkType: TalkType;
  title: string;
  overview: string;
  time: string;
  speaker: Speaker;
};

export const talkList: Talk[] = [
  {
    id: "1",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "SESSION",
    title: "tscからtsgoへ ── DenoのTypeScript基盤はどう変わったか",
    overview: "",
    time: "11:10 〜 11:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "2",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "SESSION",
    title: "「関数型プログラミング」を分解する.ts",
    overview: "",
    time: "11:10 〜 11:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "3",
    eventDate: "DAY1",
    track: "TRACK3",
    talkType: "SESSION",
    title:
      "開発体験を左右するライブラリの API 設計 ― GraphQL スキーマ構築ライブラリから考える",
    overview: "",
    time: "11:10 〜 11:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "4",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "SESSION",
    title: "業務に残された「よくない型」で考える「TypeScriptの難しさ」",
    overview: "",
    time: "11:50 〜 12:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "5",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "SESSION",
    title: '関係性から理解する"同一性"の型用語たち',
    overview: "",
    time: "11:50 〜 12:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "6",
    eventDate: "DAY1",
    track: "TRACK3",
    talkType: "SESSION",
    title: "TypeScriptの「型」をAIのスキルに昇華させてみた件について",
    overview: "",
    time: "11:50 〜 12:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "7",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "SESSION",
    title: "TypeScriptでWebAssemblyを用いた型安全なプラグイン設計",
    overview: "",
    time: "13:40 〜 14:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "8",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "SESSION",
    title: "権限チェックの一貫性を型で守る TypeScript による多層防御",
    overview: "",
    time: "13:40 〜 14:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "9",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title:
      "TypeScriptとAngular Signal で実現する保守性の高いアプリケーション設計 - 3層アーキテクチャによる責務分離の実践",
    overview: "",
    time: "14:20 〜 14:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "10",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title:
      "checker.tsにチキンレース仕掛けてみた：型エラー(TS2589)が発生する境界線を求めて",
    overview: "",
    time: "14:20 〜 14:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "11",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title: "ReactとSvelteのその先、Ripple-TS",
    overview: "",
    time: "14:30 〜 14:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "12",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title: "型の深宇宙へ飛び込め ─ tscを遅くする記述パターンの全解剖 ─",
    overview: "",
    time: "14:30 〜 14:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "13",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title: "型で頑張るプロダクト国際化",
    overview: "",
    time: "14:40 〜 14:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "14",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title:
      "決定論的な型チェックへ：Go 製コンパイラによる10倍速の裏側で --stableTypeOrdering から見える並列化への挑戦",
    overview: "",
    time: "14:40 〜 14:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "15",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "SESSION",
    title:
      "TypeScriptのclassはなぜこうなったのか — 歴史・落とし穴・そして使いどころを探る",
    overview: "",
    time: "15:10 〜 15:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "16",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "SESSION",
    title: "アンチパターンを避ける型駆動React最適化",
    overview: "",
    time: "15:10 〜 15:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "17",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "SESSION",
    title: "ビジネスモデルから紐解く、AI+型駆動開発",
    overview: "",
    time: "15:50 〜 16:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "18",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "SESSION",
    title: "Stage 3 Decorators でできること / できないこと",
    overview: "",
    time: "15:50 〜 16:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "19",
    eventDate: "DAY1",
    track: "TRACK3",
    talkType: "SESSION",
    title:
      "TypeScriptだけでAIエージェントを作る ― フロント・エージェント・インフラのフルスタック実践",
    overview: "",
    time: "15:50 〜 16:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "20",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title: "密結合なバックエンドから TypeScript のコードを生成する",
    overview: "",
    time: "16:40 〜 16:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "21",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title: "TanStack StartのcreateServerFnで作る、型が通るAPI",
    overview: "",
    time: "16:40 〜 16:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "22",
    eventDate: "DAY1",
    track: "TRACK3",
    talkType: "SESSION",
    title: "プラグインで拡張されるContextをtype-safeにする難しさと設計判断",
    overview: "",
    time: "16:40 〜 17:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "23",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title:
      "TypeSpecで繋ぐ複数プロダクトの型安全 — スキーマ共有による「型契約」の実践",
    overview: "",
    time: "16:50 〜 17:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "24",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title:
      "実践TanStack Start: 新規プロダクトを開発して確立した、サーバーとクライアント境界の設計パターン",
    overview: "",
    time: "16:50 〜 17:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "25",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title:
      "TypeScriptの型はAIに届いているか？ ― AIコーディングツール検証で見えたIDEとの断絶",
    overview: "",
    time: "17:00 〜 17:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "26",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title: "TanStack Router の型定義を読み解く",
    overview: "",
    time: "17:00 〜 17:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "27",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title:
      "TypeScriptエンジニアのためのWASMランタイム入門：AssemblyScriptで実装から理解するメモリの実態",
    overview: "",
    time: "17:20 〜 17:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "28",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title: "Zod v4 codec でスキーマに型変換を埋め込む REST API 設計",
    overview: "",
    time: "17:20 〜 17:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "29",
    eventDate: "DAY1",
    track: "TRACK3",
    talkType: "LT",
    title:
      'TypeScriptの型だけでオセロを完全実装する ── 型は"仕様"をどこまで語れるか',
    overview: "",
    time: "17:20 〜 17:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "30",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title: "Oxlint は ESLint / typescript-eslint を置き換えられるか？",
    overview: "",
    time: "17:30 〜 17:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "31",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title:
      "Road to contibuter of Valibot - ValibotにISBN validationを追加するまで -",
    overview: "",
    time: "17:30 〜 17:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "32",
    eventDate: "DAY1",
    track: "TRACK3",
    talkType: "LT",
    title: "TypeScript の型で副作用の実行順序を制御する",
    overview: "",
    time: "17:30 〜 17:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "33",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "LT",
    title: "Oxlintはいかにしてtsgolintのlint ruleを呼び出しているのか",
    overview: "",
    time: "17:40 〜 17:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "34",
    eventDate: "DAY1",
    track: "TRACK2",
    talkType: "LT",
    title: "Navigation APIがlib.dom.d.tsに採用されるまでの道のり",
    overview: "",
    time: "17:40 〜 17:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "35",
    eventDate: "DAY1",
    track: "TRACK3",
    talkType: "LT",
    title:
      "「雰囲気tsconfig」からの脱却：pnpmモノレポ運用で学び直したProject Referencesの基礎と実践",
    overview: "",
    time: "17:40 〜 17:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "36",
    eventDate: "DAY1",
    track: "TRACK1",
    talkType: "INVITATION",
    title: "基調講演『TS 7: How We Got There』",
    overview: "",
    time: "18:00 〜 18:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "37",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "SESSION",
    title: "TypeScriptコンパイラの設計考古学",
    overview: "",
    time: "11:10 〜 11:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "38",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "SESSION",
    title:
      "400超のデータポイントを型で制す —— UPSIDERの与信審査エンジンを支えるTypeScriptの「柔軟性」と「結合力」",
    overview: "",
    time: "11:10 〜 11:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "39",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "SESSION",
    title:
      "AIのために、AIを使った、Effect-TSからの脱却 〜テストを活用した安全なリファクタリングの進め方〜",
    overview: "",
    time: "11:10 〜 11:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "40",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title:
      "React の props は値の集合ではない — UI の状態を宣言するコンポーネント設計",
    overview: "",
    time: "11:50 〜 12:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "41",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title:
      "OSSのコードベースにneverthrowを漸進的に導入して、AIにも人間にも優しいエラーハンドリングを実現する",
    overview: "",
    time: "11:50 〜 12:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "42",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title:
      "10秒のビルドを1秒へ：tsdown が切り拓く 2026 年の TypeScript ライブラリ開発",
    overview: "",
    time: "11:50 〜 12:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "43",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title: "型プラグインシステムの実装に使われるテクニック",
    overview: "",
    time: "12:00 〜 12:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "44",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title:
      "LLM時代のリファクタリング戦略：AIエージェントによる段階的・安全なTS移行方法",
    overview: "",
    time: "12:00 〜 12:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "45",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title: "JSで実装した自作プログラミング言語をTSに移行した話",
    overview: "",
    time: "12:00 〜 12:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "46",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title:
      "Auth.jsからBetter Authへの移行に見る「型とランタイム」の設計思想の変化",
    overview: "",
    time: "12:10 〜 12:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "47",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title:
      "コーディングエージェントはTypeScriptの型エラーをどう自己修正しているのか",
    overview: "",
    time: "12:10 〜 12:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "48",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title: "TypeScriptでドット絵エディタ実装録: 状態設計と実装判断",
    overview: "",
    time: "12:10 〜 12:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "49",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "SESSION",
    title: "Real World Effect-TS: 堅牢なプロダクトを型で組み上げる",
    overview: "",
    time: "13:40 〜 14:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "50",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "SESSION",
    title: "tsserverとは何だったのか、これからどうなるのか",
    overview: "",
    time: "13:40 〜 14:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "51",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "SESSION",
    title: "TypeScriptでPlatform SDKを作る技術",
    overview: "",
    time: "13:40 〜 14:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "52",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title: "ts-morph でプロジェクト固有のアーキテクチャガードレールを作る",
    overview: "",
    time: "14:20 〜 14:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "53",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title: "Node.js+TypeScriptにおけるCJS/ESM相互運用の最新ポイント",
    overview: "",
    time: "14:20 〜 14:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "54",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title: "AIエージェントと協働するCLI開発 — BunとOpenClawで学んだこと",
    overview: "",
    time: "14:20 〜 14:30",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "55",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title: "typescript-goで変わるリンターの世界 — Flintという第三の選択肢",
    overview: "",
    time: "14:30 〜 14:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "56",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title: "enum よ、さようなら",
    overview: "",
    time: "14:30 〜 14:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "57",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title: "自動レビューエンジンの実装と運用 ~レビューのない世界へ~",
    overview: "",
    time: "14:30 〜 14:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "58",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title:
      "Polymorphic Components パターンで作る、型安全でセマンティックなUIコンポーネント",
    overview: "",
    time: "14:40 〜 14:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "59",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title: "inferと仲良くなる10分間",
    overview: "",
    time: "14:40 〜 14:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "60",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title:
      "Hono RPCとDrizzle ORMで実現する、AIにも優しいTypeScriptファーストな開発",
    overview: "",
    time: "14:40 〜 14:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "61",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "SESSION",
    title: "AI時代に考えたい、Branded Typesで実現する堅牢な型付け",
    overview: "",
    time: "15:10 〜 15:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "62",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "SESSION",
    title:
      "いつテストを書くか？―ソフトウェア開発における安心と不安について考える",
    overview: "",
    time: "15:10 〜 15:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "63",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "SESSION",
    title:
      "TypeScriptバックエンドのオブザーバビリティ戦略 — Datadog × NestJSの実践",
    overview: "",
    time: "15:10 〜 15:40",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "64",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "SESSION",
    title:
      "次世代リンターで探る、tsgo 時代における型認識カスタムルールの現実解",
    overview: "",
    time: "15:50 〜 16:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "65",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "SESSION",
    title:
      "静的解析への投資がAI時代のコード品質を支える ── カスタムESLintルールの設計と運用",
    overview: "",
    time: "15:50 〜 16:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "66",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "SESSION",
    title:
      "柔軟なPDFレイアウトエディタを支える型システム設計 — Discriminated UnionとConditional Typeの実践",
    overview: "",
    time: "15:50 〜 16:20",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "67",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title: "childrenの順序まで型で縛る ── Branded Typesで実践するJSXの構造安全",
    overview: "",
    time: "16:40 〜 16:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "68",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title: "これから非推奨になる設定・コードと代替について",
    overview: "",
    time: "16:40 〜 16:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "69",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title: "Typiaで配信JSONの安全性を構造的に担保する",
    overview: "",
    time: "16:40 〜 16:50",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "70",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title:
      "スプレッド構文によるブランド流出問題を乗り越えて、オブジェクト型に対する Branded Types を使い倒す",
    overview: "",
    time: "16:50 〜 17:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "71",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title: "TypeScript Compiler はどのように未使用変数を検出しているのか？",
    overview: "",
    time: "16:50 〜 17:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "72",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title: "バックエンドにElysiaJSを採用して気付いた、良い点・悪い点",
    overview: "",
    time: "16:50 〜 17:00",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "73",
    eventDate: "DAY2",
    track: "TRACK1",
    talkType: "LT",
    title: "string地獄を脱出する — ValueObject + Zod 実践パターン",
    overview: "",
    time: "17:00 〜 17:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "74",
    eventDate: "DAY2",
    track: "TRACK2",
    talkType: "LT",
    title:
      "プロパティの順序で型推論が壊れる！？ TS6.0の修正からContext-Sensitivityの仕組みを追う",
    overview: "",
    time: "17:00 〜 17:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
  {
    id: "75",
    eventDate: "DAY2",
    track: "TRACK3",
    talkType: "LT",
    title:
      "型のないDSLを安全に扱う: TypeScriptとメタプログラミングによるElasticsearch連携の実践",
    overview: "",
    time: "17:00 〜 17:10",
    speaker: {
      name: "IIHARA HODAKA",
      username: "IIHARA議長",
      bio: "WOTA Corp. web engineer.",
      xId: "iihara_gityo",
      githubId: "Gityosan",
      profileImagePath: "logo.svg",
      additionalLink: undefined,
      affiliation: "WOTA Corp.",
      position: "フルスタックエンジニア",
    },
  },
];

export const talkIds = talkList.map((talk) => ({
  id: talk.id,
}));
