name: サイドイベント追加
description: サイドイベントをWebサイトに追加する
labels: ["side-event"]
body:
  - type: markdown
    attributes:
      value: |
        サイドイベントの情報を入力してください。
        このイシューが作成されると、自動的にPRが作成されます。

  - type: input
    id: date
    attributes:
      label: 開催日
      description: 表示用の日付形式
      placeholder: "2/9 (月)"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: イベント名
      placeholder: "TSKaigi Mashup #4 CfP勉強会"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: イベントURL
      description: ConnpassなどのイベントページURL
      placeholder: "https://typescript-jpc.connpass.com/event/379927/"
    validations:
      required: true

  - type: input
    id: thumbnail
    attributes:
      label: サムネイルURL
      description: イベントのサムネイル画像URL
      placeholder: "https://media.connpass.com/thumbs/..."
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: イベント詳細
      description: イベントの説明文
      placeholder: |
        TSKaigi採択者によるトークと、TSKaigiのCfP選考担当者によるトークを通じて、CfP応募のコツや選考のポイントを学べる勉強会です。
        初めてCfPに応募しようと考えている方、応募を迷っている・応募に自信がない方におすすめです。
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: タグ（カンマ区切り）
      description: 任意。複数ある場合はカンマで区切ってください
      placeholder: "勉強会, CfP"
    validations:
      required: false

  - type: input
    id: sponsors
    attributes:
      label: スポンサー（カンマ区切り）
      description: 複数ある場合はカンマで区切ってください
      placeholder: "TSKaigi Association"
    validations:
      required: true

  - type: input
    id: finished_at
    attributes:
      label: 終了日時（ISO形式）
      description: イベント終了後に非表示にするための日時
      placeholder: "2026-02-09T21:30:00+09:00"
    validations:
      required: true
