import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

export type GenerateStaffListOptions = {
  dir: string;
  outputFile: string;
  listName: string;
  typeName: string;
  varPrefix: string;
};

export type GenerateStaffListResult = {
  outputFile: string;
  entries: number;
};

/**
 * `dir` 配下の *.json から TypeScript の一覧ファイルを生成する。
 * staff / day-staff の双方で共通。
 */
export function generateStaffList(
  options: GenerateStaffListOptions,
): GenerateStaffListResult {
  const { dir, outputFile, listName, typeName, varPrefix } = options;

  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const files = readdirSync(dir)
    .filter((file) => file.endsWith(".json"))
    .sort((a, b) => a.localeCompare(b, "en", { numeric: true }));

  const baseName = path.basename(dir);
  const imports = files.map((file) => {
    const id = file.replace(".json", "");
    return `import ${varPrefix}${id} from "./${baseName}/${file}";`;
  });

  const entries = files.map((file) => {
    const id = file.replace(".json", "");
    return `  ${varPrefix}${id},`;
  });

  const importSection = imports.length > 0 ? `\n${imports.join("\n")}\n` : "";

  const output = `/* eslint-disable */
// This file is auto-generated by scripts/commands/staff-list.ts.
// Do not edit manually.
${importSection}
export type ${typeName} = {
  name: string;
  image: string;
  href?: string;
};

export const ${listName}: ${typeName}[] = [${entries.length > 0 ? `\n${entries.join("\n")}\n` : ""}];
`;

  writeFileSync(outputFile, output, "utf8");
  return { outputFile, entries: files.length };
}
